<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAWBCbNH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAWBCbNH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAWBCbNH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAWBCbNH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAWBCbNH\App_KernelDevDebugContainer([
    'container.build_hash' => 'AWBCbNH',
    'container.build_id' => '3563d14a',
    'container.build_time' => 1634048064,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAWBCbNH');
