<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFqu3GiF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFqu3GiF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFqu3GiF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFqu3GiF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFqu3GiF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fqu3GiF',
    'container.build_id' => '05ca14bf',
    'container.build_time' => 1634205107,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFqu3GiF');
