<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWGfNWcA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWGfNWcA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWGfNWcA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWGfNWcA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWGfNWcA\App_KernelDevDebugContainer([
    'container.build_hash' => 'WGfNWcA',
    'container.build_id' => 'daca2b9a',
    'container.build_time' => 1635121020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWGfNWcA');
